# Работает без docker-compose. Если раскомитить, то при запуске docker-compose он не будет ссылаться на этот хост.
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8282/eureka

spring:
  main:
    allow-bean-definition-overriding: true
    web-application-type: none
  datasource:
    platform: postgres
#    url: jdbc:postgresql://172.17.0.1:5432/netflix_oss?currentSchema=netflix_oss
    url: jdbc:postgresql://127.0.0.1:5001/postgres?currentSchema=netflix_oss
    username: postgres
    password: 147258369
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        greetings-in:
          destination: greetings
          contentType: application/json
        greetings-out:
          destination: greetings
          contentType: application/json

  kafka:
    consumer:
      group-id: employee-api
      auto-offset-reset: earliest
      enable-auto-commit: false
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      batch-size: 16384
      buffer-memory: 33554432
      retries: 0
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

