server:
  port: 9093

spring:
  kafka:
    bootstrap-servers: '127.0.0.1:9092'
    topic: employees

integration:
  dir:
    path: "/data/employees/"
    refresh: 30000
    maxMessages: 5
    fileDelimiter: ';'

eureka:
  server:
    maxThreadsForPeerReplication: 0
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false